/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benxiang_jintest_OpenAndCloseJNI */

#ifndef _Included_com_benxiang_jintest_OpenAndCloseJNI
#define _Included_com_benxiang_jintest_OpenAndCloseJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benxiang_jintest_OpenAndCloseJNI
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_benxiang_jintest_OpenAndCloseJNI_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_benxiang_jintest_OpenAndCloseJNI
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_benxiang_jintest_OpenAndCloseJNI_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
